branches:
  only:
    - master
    - experimental
matrix:
  include:
    # Linux
    - language: cpp
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      before_install:
        - eval "CC=gcc-8 && CXX=g++-8"
        - eval "PATH=${PATH}:$HOME/.local/bin"
        - pip install --user cpplint
      script:
        - (cd lightcone && ./configure && make lint && make && make test)
        - (cd example/benchmark && ./configure && make lint && make)
        - (cd example/httpd && ./configure && make lint && make)
    # OSX
    - language: cpp
      os: osx
      osx_image: xcode10.1
      script:
        - (cd lightcone && ./configure && make && make test)
        - (cd example/benchmark && ./configure && make)
        - (cd example/httpd && ./configure && make)
notifications:
  email: false
