branches:
  only:
    - master
matrix:
  include:
    # Linux
    - language: cpp
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
      before_install:
        - eval "${MATRIX_EVAL}"
        - eval "PATH=${PATH}:$HOME/.local/bin"
        - pip install --user cpplint
      script:
        - (cd liblightcone && ./configure && make lint && make && make test)

    # OSX
    - language: cpp
      os: osx
      osx_image: xcode9
      script:
        - (cd liblightcone && ./configure && make && make test)

notifications:
  email: false
